services:
  - type: web
    name: peptide-characterization-api
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://radhikasahai.github.io
